//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Svn.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Content Sanitization failed. You are requested to contact administrator..
        /// </summary>
        public static string AllowXssSafeHtmlAttributeErrorMessage {
            get {
                return ResourceManager.GetString("AllowXssSafeHtmlAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a draft version available for this Article. Please complete that first or delete..
        /// </summary>
        public static string AlreadyDraftVersionOfSameArticleAvailable {
            get {
                return ResourceManager.GetString("AlreadyDraftVersionOfSameArticleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an edited version available for this Article which is in pending for admin approval status. Please proceed further based on admin response..
        /// </summary>
        public static string AlreadySubmittedVersionOfSameArticleAvailable {
            get {
                return ResourceManager.GetString("AlreadySubmittedVersionOfSameArticleAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This article is already in approved status.
        /// </summary>
        public static string ArticleFromApproved2Approved {
            get {
                return ResourceManager.GetString("ArticleFromApproved2Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This article cannot be approved as it is deleted state.
        /// </summary>
        public static string ArticleFromDeleted2Approved {
            get {
                return ResourceManager.GetString("ArticleFromDeleted2Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This article is already in deleted status.
        /// </summary>
        public static string ArticleFromDeleted2Deleted {
            get {
                return ResourceManager.GetString("ArticleFromDeleted2Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing is not allowed on this article as it is in deleted state.
        /// </summary>
        public static string ArticleFromDeleted2Draft {
            get {
                return ResourceManager.GetString("ArticleFromDeleted2Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing is not allowed on this article as it is in deleted state.
        /// </summary>
        public static string ArticleFromDeleted2Submitted {
            get {
                return ResourceManager.GetString("ArticleFromDeleted2Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafted Article can not be approved.
        /// </summary>
        public static string ArticleFromDraft2Approved {
            get {
                return ResourceManager.GetString("ArticleFromDraft2Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing is not allowed on this article as it is in pending for admin approval status.
        /// </summary>
        public static string ArticleFromSubmitted2Draft {
            get {
                return ResourceManager.GetString("ArticleFromSubmitted2Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing is not allowed on this article as it is in pending for admin approval status.
        /// </summary>
        public static string ArticleFromSubmitted2Submitted {
            get {
                return ResourceManager.GetString("ArticleFromSubmitted2Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not found.
        /// </summary>
        public static string ArticleNotFound {
            get {
                return ResourceManager.GetString("ArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity cannot be null.
        /// </summary>
        public static string EntityCannotBeNull {
            get {
                return ResourceManager.GetString("EntityCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cannot be null.
        /// </summary>
        public static string IDCannotBeNull {
            get {
                return ResourceManager.GetString("IDCannotBeNull", resourceCulture);
            }
        }
    }
}
